name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: MVN clean install
      run: mvn -B clean install

    - name: Create Jacoco branch and upload report
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git checkout -b jacoco-reports-v2
        git pull origin jacoco-reports-v2
        ls
        find . -mindepth 1 -maxdepth 1 ! -path "./target/site/jacoco" ! -path "./.git" -exec rm -r {} \;
        ls
        git add -A
        ls
        git commit -m "Add Jacoco report"
        git push origin jacoco-reports-v2
